#!/usr/bin/env node

// Mines User vocab (the language the user actually types) out of past session
// transcripts, so /setup-sk-skills can propose glossary terms instead of
// leaving CONTEXT.md empty. Reads Claude Code and Codex transcripts, prints a
// ranked shortlist to stdout, and writes nothing anywhere.

import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, sep } from "node:path";
import { homedir } from "node:os";
import { execFileSync } from "node:child_process";

// Every harness slips text it generated itself into the user's turn. None of it
// is the user's vocabulary, and left in it dominates the ranking.
const INJECTED_TAGS = [
  "task-notification",
  "system-reminder",
  "command-name",
  "command-message",
  "command-args",
  "command-contents",
  "local-command-stdout",
  "local-command-stderr",
  "user-prompt-submit-hook",
  "ide_diagnostics",
  "ide_selection",
  "bash-input",
  "bash-stdout",
  "bash-stderr",
];

const INJECTED_SPANS = INJECTED_TAGS.map((tag) => new RegExp(`<${tag}>[\\s\\S]*?<\\/${tag}>`, "g"));

// Preambles the harness writes into the user role at a session boundary.
const PREAMBLES = [
  /^This session is being continued from a previous conversation/i,
  /^Caveat: The messages below were generated by the user while running local commands/i,
  /^Analysis:/,
];

const stripInjectedSpans = (text) => {
  const stripped = INJECTED_SPANS.reduce((acc, span) => acc.replace(span, " "), text).trim();
  // An unclosed or unknown wrapper tag still means the harness wrote it, not you.
  if (/^<[a-z][a-z0-9_-]*>/i.test(stripped)) return "";
  // So do the bracketed markers a harness leaves where a turn was cut short.
  if (/^\[(request interrupted|tool use|no response|user has|the user)/i.test(stripped)) return "";
  if (PREAMBLES.some((preamble) => preamble.test(stripped))) return "";
  return stripped;
};

const parseJsonl = (source) => {
  const records = [];
  for (const line of String(source).split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      records.push(JSON.parse(trimmed));
    } catch {
      // A truncated trailing line is normal in a live session file.
    }
  }
  return records;
};

const textFromContent = (content) => {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return content
    .filter((block) => block && block.type === "text" && typeof block.text === "string")
    .map((block) => block.text)
    .join("\n");
};

/**
 * Claude Code writes one JSONL per session under ~/.claude/projects/<cwd-slug>/.
 * Slash-command bodies arrive as user records flagged isMeta; subagent turns are
 * flagged isSidechain; tool results arrive as user records too. None of those are
 * words the user typed.
 */
export const extractClaudeTurns = (source) => {
  const turns = [];
  for (const record of parseJsonl(source)) {
    if (!record || record.type !== "user") continue;
    if (record.isMeta || record.isSidechain) continue;
    const message = record.message;
    if (!message || message.role !== "user") continue;
    const text = stripInjectedSpans(textFromContent(message.content));
    if (text) turns.push(text);
  }
  return turns;
};

/**
 * Codex writes date-foldered rollouts under ~/.codex/sessions/<Y>/<M>/<D>/.
 * AGENTS.md instruction blobs and environment context are injected into the
 * user role there, so they are filtered by their wrapper tags and headings.
 */
const CODEX_INJECTED = [
  /^#\s*AGENTS\.md instructions/i,
  /^<INSTRUCTIONS>/,
  /^<environment_context>/,
  /^<user_instructions>/,
  /^<project_doc>/,
];

export const extractCodexTurns = (source) => {
  const turns = [];
  for (const record of parseJsonl(source)) {
    if (!record) continue;
    const payload = record.type === "response_item" ? record.payload : record;
    if (!payload || payload.type !== "message" || payload.role !== "user") continue;
    const content = Array.isArray(payload.content)
      ? payload.content
          .filter((block) => block && typeof block.text === "string" && block.type !== "output_text")
          .map((block) => block.text)
          .join("\n")
      : textFromContent(payload.content);
    const text = stripInjectedSpans(content);
    if (!text) continue;
    if (CODEX_INJECTED.some((pattern) => pattern.test(text))) continue;
    turns.push(text);
  }
  return turns;
};

// A phrase is only worth proposing if it reads like a name for something. These
// are the words that show up at the edges of every English sentence and never
// carry the domain.
const STOPWORDS = new Set(
  ("a an and are as at be been but by can could do does did for from get go had has have he her him his how i if in "
    + "is it its just let like make me my no not now of on once one only or our out over please put run see she should "
    + "so some that the their them then there these they this those to too try up us use was we were what when where "
    + "which who why will with would you your yes ok okay thanks now still also very much more most any every each "
    + "here again back into than about after before while all its it's im i'm dont don't cant can't "
    + "ran runs run fired broke works work fails failed fixed added removed updated needs need want think "
    + "know said says using used doing done going looks look seems keep keeps got make made")
    .split(" "),
);

const NOISE = new Set(["file", "files", "line", "lines", "code", "thing", "things", "stuff", "way", "bit"]);

const normalise = (text) =>
  text
    .toLowerCase()
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`[^`]*`/g, " ")
    .replace(/https?:\/\/\S+/g, " ")
    .replace(/[^a-z0-9'\-\s]/g, " ");

const phrasesFrom = (text, { min = 2, max = 3 } = {}) => {
  const found = [];
  for (const chunk of normalise(text).split(/\s{2,}|\n+/)) {
    const words = chunk.split(/\s+/).filter(Boolean);
    for (let n = min; n <= max; n += 1) {
      for (let i = 0; i + n <= words.length; i += 1) {
        const window = words.slice(i, i + n);
        if (STOPWORDS.has(window[0]) || STOPWORDS.has(window[n - 1])) continue;
        if (window.some((w) => w.length < 3 || !/[a-z]{3}/.test(w))) continue;
        if (NOISE.has(window[n - 1])) continue;
        found.push(window.join(" "));
      }
    }
  }
  return found;
};

/** Reads an existing CONTEXT.md so the miner never re-proposes settled language. */
export const parseGlossary = (markdown = "") => {
  const terms = [];
  const avoided = [];
  for (const line of String(markdown).split("\n")) {
    const term = line.match(/^\*\*(.+?)\*\*\s*:?\s*$/);
    if (term) {
      terms.push(term[1].toLowerCase().trim());
      continue;
    }
    const avoid = line.match(/^_Avoid_:\s*(.+)$/i);
    if (avoid) {
      for (const synonym of avoid[1].split(",")) {
        const cleaned = synonym.replace(/[*_`]/g, "").toLowerCase().trim();
        if (cleaned) avoided.push(cleaned);
      }
    }
  }
  return { terms, avoided };
};

// Synonyms of one thing usually differ at the front and agree at the back, so
// the last two words are what group them.
const clusterKey = (term) => term.split(" ").slice(-2).join(" ");

/**
 * Scores candidate terms across sessions. Spread across separate sessions counts
 * for more than raw repetition (a phrase used ten times in one long session is
 * jargon of the moment; one used across five sessions is real vocabulary), and a
 * phrase the codebase also uses is a grounded domain noun rather than an aside.
 */
const singularise = (phrase) => phrase.replace(/(\w{3,})(ies)\b/g, "$1y").replace(/(\w{3,}[^s])s\b/g, "$1");

export const rankTerms = (sessions, { glossary = { terms: [], avoided: [] }, codeText = "", limit = 40 } = {}) => {
  const known = new Set(
    [...(glossary.terms || []), ...(glossary.avoided || [])].flatMap((term) => [term, singularise(term)]),
  );
  const stats = new Map();

  sessions.forEach((turns, sessionIndex) => {
    for (const turn of turns) {
      for (const phrase of phrasesFrom(turn)) {
        if (known.has(phrase) || known.has(singularise(phrase))) continue;
        let entry = stats.get(phrase);
        if (!entry) {
          entry = { term: phrase, count: 0, sessionIds: new Set(), evidence: [] };
          stats.set(phrase, entry);
        }
        entry.count += 1;
        entry.sessionIds.add(sessionIndex);
        if (entry.evidence.length < 3) {
          const quote = turn.length > 220 ? `${turn.slice(0, 217)}...` : turn;
          if (!entry.evidence.includes(quote)) entry.evidence.push(quote);
        }
      }
    }
  });

  const codeHaystack = normalise(codeText);
  const compactCode = codeText.toLowerCase().replace(/[^a-z0-9]/g, "");

  const candidates = [];
  for (const entry of stats.values()) {
    if (entry.count < 2) continue;
    const sessionCount = entry.sessionIds.size;
    const inCode =
      codeHaystack.includes(entry.term) || compactCode.includes(entry.term.replace(/[^a-z0-9]/g, ""));
    const score = entry.count * (1 + Math.log2(sessionCount)) * (inCode ? 1.5 : 1);
    candidates.push({
      term: entry.term,
      count: entry.count,
      sessions: sessionCount,
      inCode,
      score: Number(score.toFixed(2)),
      evidence: entry.evidence,
      avoid: [],
    });
  }

  candidates.sort((a, b) => b.score - a.score || a.term.localeCompare(b.term));

  // A shorter phrase that almost only ever appears inside a longer one is not a
  // term of its own: "lead sweeper" inside "stuck lead sweeper" is the same
  // thing said with less of the name.
  const contained = new Set();
  for (const shorter of candidates) {
    let inLonger = 0;
    for (const longer of candidates) {
      if (shorter === longer || longer.term.length <= shorter.term.length) continue;
      if (` ${longer.term} `.includes(` ${shorter.term} `)) inLonger += longer.count;
    }
    if (inLonger >= shorter.count) contained.add(shorter.term);
  }

  // Near-synonyms are the payoff: transcripts are the one place you can see the
  // same thing called three names. The strongest becomes the term, the rest
  // become its _Avoid_ line.
  const dominantByHead = new Map();
  const clustered = [];
  for (const candidate of candidates) {
    if (contained.has(candidate.term)) continue;
    const head = clusterKey(candidate.term);
    const dominant = dominantByHead.get(head);
    if (dominant && dominant.term !== candidate.term) {
      dominant.avoid.push(candidate.term);
      continue;
    }
    dominantByHead.set(head, candidate);
    clustered.push(candidate);
  }

  return clustered.slice(0, limit);
};

// ---------------------------------------------------------------------------
// Session discovery and CLI
// ---------------------------------------------------------------------------

/**
 * Claude Code names a session directory after the working directory it was
 * started in, with separators and dots flattened to hyphens. A git worktree is a
 * different working directory, so it lands in a sibling directory whose name
 * starts with the repo's own slug.
 */
export const claudeSlug = (cwd) => cwd.split(sep).join("-").replace(/\./g, "-");

const readJsonlFile = (path) => {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return "";
  }
};

const listFiles = (dir, predicate, out = []) => {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) listFiles(full, predicate, out);
    else if (predicate(full)) out.push(full);
  }
  return out;
};

const withMtime = (paths) =>
  paths
    .map((path) => {
      try {
        const stat = statSync(path);
        return { path, mtime: stat.mtimeMs, size: stat.size };
      } catch {
        return null;
      }
    })
    .filter(Boolean)
    .sort((a, b) => b.mtime - a.mtime);

export const findClaudeSessions = (cwd, home = homedir()) => {
  const projects = join(home, ".claude", "projects");
  if (!existsSync(projects)) return [];
  const slug = claudeSlug(cwd);
  const dirs = readdirSync(projects, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.startsWith(slug))
    .map((entry) => join(projects, entry.name));
  return withMtime(dirs.flatMap((dir) => listFiles(dir, (p) => p.endsWith(".jsonl"))));
};

export const findCodexSessions = (cwd, home = homedir()) => {
  const sessions = join(home, ".codex", "sessions");
  if (!existsSync(sessions)) return [];
  const rollouts = withMtime(listFiles(sessions, (p) => p.endsWith(".jsonl")));
  return rollouts.filter((file) => {
    const head = readJsonlFile(file.path).split("\n", 1)[0] || "";
    if (!head.includes('"session_meta"')) return false;
    try {
      const meta = JSON.parse(head);
      const sessionCwd = meta?.payload?.cwd || "";
      return claudeSlug(sessionCwd).startsWith(claudeSlug(cwd));
    } catch {
      return false;
    }
  });
};

const READABLE = /\.(md|mdx|txt|js|mjs|cjs|jsx|ts|tsx|py|rb|php|go|rs|java|kt|swift|sql|yaml|yml|json|vue|svelte)$/i;

/**
 * The codebase is a witness: a phrase the project already writes down is a
 * grounded domain noun rather than an aside. Both what the files are called and
 * what they say count, so this reads the paths and a bounded slice of contents.
 */
const repoText = (cwd) => {
  try {
    const files = execFileSync("git", ["-C", cwd, "ls-files"], { encoding: "utf8" })
      .split("\n")
      .filter(Boolean)
      .filter((f) => !/(^|\/)(node_modules|dist|build|vendor)\//.test(f))
      .slice(0, 4000);
    const parts = [files.join("\n")];
    let budget = 4_000_000;
    for (const file of files) {
      if (budget <= 0) break;
      if (!READABLE.test(file)) continue;
      try {
        const contents = readFileSync(join(cwd, file), "utf8");
        if (contents.length > budget) continue;
        budget -= contents.length;
        parts.push(contents);
      } catch {
        // Unreadable or binary despite the extension; the paths still count.
      }
    }
    return parts.join("\n");
  } catch {
    return "";
  }
};

const parseArgs = (argv) => {
  const options = { cwd: process.cwd(), maxSessions: 50, maxBytes: 500_000_000, json: false, countOnly: false };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--cwd") options.cwd = argv[++i];
    else if (arg === "--max-sessions") options.maxSessions = Number(argv[++i]);
    else if (arg === "--max-bytes") options.maxBytes = Number(argv[++i]);
    else if (arg === "--json") options.json = true;
    else if (arg === "--count-only") options.countOnly = true;
  }
  return options;
};

export const mine = (options) => {
  const { cwd, maxSessions, maxBytes, countOnly } = options;
  const claude = findClaudeSessions(cwd).map((f) => ({ ...f, harness: "claude" }));
  const codex = findCodexSessions(cwd).map((f) => ({ ...f, harness: "codex" }));
  const all = [...claude, ...codex].sort((a, b) => b.mtime - a.mtime);

  const used = [];
  let bytes = 0;
  for (const file of countOnly ? [] : all) {
    if (used.length >= maxSessions || bytes + file.size > maxBytes) break;
    used.push(file);
    bytes += file.size;
  }

  const sessions = used.map((file) => {
    const raw = readJsonlFile(file.path);
    return file.harness === "claude" ? extractClaudeTurns(raw) : extractCodexTurns(raw);
  });

  const contextPath = join(cwd, "CONTEXT.md");
  const glossary = existsSync(contextPath) ? parseGlossary(readFileSync(contextPath, "utf8")) : { terms: [], avoided: [] };

  return {
    found: { claude: claude.length, codex: codex.length },
    read: used.length,
    skipped: all.length - used.length,
    turns: sessions.reduce((sum, turns) => sum + turns.length, 0),
    glossaryTerms: glossary.terms.length,
    candidates: rankTerms(sessions, { glossary, codeText: repoText(cwd) }),
  };
};

const formatReport = (result) => {
  const lines = [];
  lines.push(
    `Sessions found: ${result.found.claude} Claude Code, ${result.found.codex} Codex. `
      + `Read ${result.read}, skipped ${result.skipped}. Typed turns: ${result.turns}. `
      + `Existing glossary terms: ${result.glossaryTerms}.`,
  );
  if (!result.candidates.length) {
    lines.push("");
    lines.push("No candidate terms passed the threshold.");
    return lines.join("\n");
  }
  lines.push("");
  for (const [index, candidate] of result.candidates.entries()) {
    lines.push(
      `${index + 1}. ${candidate.term}  [used ${candidate.count}x across ${candidate.sessions} session(s)`
        + `${candidate.inCode ? ", also in the codebase" : ""}, score ${candidate.score}]`,
    );
    if (candidate.avoid.length) lines.push(`   also called: ${candidate.avoid.join(", ")}`);
    for (const quote of candidate.evidence.slice(0, 2)) lines.push(`   > ${quote.replace(/\s+/g, " ")}`);
  }
  return lines.join("\n");
};

const isMain = process.argv[1] && process.argv[1].endsWith("mine-vocab.mjs");
if (isMain) {
  const options = parseArgs(process.argv.slice(2));
  const result = mine(options);
  process.stdout.write(options.json ? `${JSON.stringify(result, null, 2)}\n` : `${formatReport(result)}\n`);
}
